spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_OAUTH_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_OAUTH_SCOPE:profile,email}

admin.password=${ADMIN_PASSWORD:1234}

spring.security.user.name=${ADMIN_BASIC_USERNAME:admin}
spring.security.user.password=${ADMIN_BASIC_PASSWORD:password}

frontend.url=${FRONTEND_URL:https://daehyun.dev}
frontend.domain=${FRONTEND_DOMAIN:daehyun.dev}
